Add read the docs
students-teach-students/python-tools-for-students pull request #32
Opened 2019-09-26 14:15 UTC by s-weigand

This PR adds this project to read the docs, so users can read it online or download the material as pdf.
I had to change the folder and file names since the ``#`` in the paths did mess up, links to binder.

@redbluee Can please review ``docs\getting_started.rst``, since this is the only text i wrote, the rest is pure tooling.

closes #19

2019-10-04 19:56 UTC, s-weigand commented
Now PDF is working 😄

2019-10-05 15:29 UTC, redbluee requested changes
nice explanation

2019-10-05 15:29 UTC, redbluee commented on docs/getting_started.rst
> +in you day to day student life installed on you computer and
**your** day to day student life installed on **your** computer

2019-10-05 15:29 UTC, redbluee commented on docs/getting_started.rst
> +Anaconda is our recommended to install python on all operating systems,
Anaconda is our **recommendation**

2019-10-05 15:29 UTC, redbluee commented on docs/getting_started.rst
> +Yet another bonus of ``conda`` is that is has a build pipeline in place,
is that **it** has a build pipeline in place

2019-10-05 15:29 UTC, redbluee commented on docs/getting_started.rst
> +you through the process tof getting the pure CPython Interpreter.
through the process ~~t~~of getting the pure CPython Interpreter

2019-10-05 15:32 UTC, s-weigand commented
thanks 😊

2019-10-05 15:51 UTC, redbluee approved these changes

2019-10-05 15:52 UTC, merged

2019-10-05 16:04 UTC, s-weigand commented
@all-contributors please add @redbluee for review

2019-10-05 16:47 UTC, s-weigand commented
@all-contributors please add @redbluee for doc infra maintenance

2019-10-05 16:52 UTC, s-weigand commented
@all-contributors please add @s-weigand for doc infra maintenance

2019-10-05 16:57 UTC, s-weigand commented
@all-contributors please add @redbluee for ideas projectManagement maintenance

2019-10-05 17:42 UTC, s-weigand commented
@all-contributors please add @s-weigand for doc infra maintenance ideas projectManagement